### ISSUE TITLE
Breakpoint stops inside internal rails/gem code

### ISSUE THREAD

**Issue by hashwin** [deivid-rodriguez/byebug#452]
## Problem description

Byebug works fine the first time I add a debugger statement, but then when _any_ other code is changed, the next time the breakpoint is hit, it seems to stop in some internal rails/other gem code. The issue is only alleviated by restarting the server, which can become time consuming when trying to debug an issue.

## Expected behavior

The breakpoint should be retained even after code is changed.

## Actual behavior

The breakpoint works fine the first time, but as soon as code is changed and the breakpoint is hit again, it seems to stop in internal rails code.

## Steps to reproduce the problem

Simple example in HomeController:

```
class HomeController < ApplicationController
  before_action :redirect_signed_in_user, only: :welcome

  def welcome; end

  def redirect_signed_in_user
    debugger
    redirect_to root_url if user_signed_in?
  end
end
```

Works as expected
```
[20, 29] in /Users/ashwinhegde/code/apps/o3_crm/app/controllers/home_controller.rb
   20:
   21:   private
   22:
   23:   def redirect_signed_in_user
   24:     debugger
=> 25:     redirect_to root_url if user_signed_in?
   26:   end
   27:
```

Change some code, any code.
Next time the breakpoint is hit - some internal devise code:

```
[117, 126] in /Users/ashwinhegde/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devise-4.4.3/lib/devise/controllers/helpers.rb
   117:             opts[:scope] = :#{mapping}
   118:             warden.authenticate!(opts) if !devise_controller? || opts.delete(:force)
   119:           end
   120:
   121:           def #{mapping}_signed_in?
=> 122:             !!current_#{mapping}
   123:           end
   124:
   125:           def current_#{mapping}
   126:             @current_#{mapping} ||= warden.authenticate(scope: :#{mapping})
(byebug)
```

**Comment by deivid-rodriguez** [comment]
Thanks for the report, I've started seeing the same thing recently too... And I have no idea why. It seems like a regression to me. Can you try `10.0.0`, `10.0.1`, and `10.0.2` and compare?

**Comment by deivid-rodriguez** [comment]
@hashwin Are you using `bootsnap` by any chance? I think `byebug` does not play nice with bootsnap.

**Comment by deivid-rodriguez** [comment]
@hashwin The following setup in `config/boot.rb` seems to work. It's the default config recommened in `bootsnap`'s README, but changing `compile_cache_iseq` to `false`

```ruby
require 'bootsnap'

env = ENV['RAILS_ENV'] || 'development'

Bootsnap.setup(
  cache_dir: 'tmp/cache',
  development_mode: env == 'development',
  load_path_cache: true,
  autoload_paths_cache: true,
  disable_trace: true,
  compile_cache_iseq: false,
  compile_cache_yaml: true
)
```

I definitely need to document this, so I'll reopen this issue and use it as a reminder.

**Comment by hashwin** [comment]
Thanks @deivid-rodriguez. I will try this and let you know if I run into more trouble.

**Comment by tzmfreedom** [comment]
Bootsnap use `RubyVM::InstructionSequence.load_from_binary` to load other file quickly, and byebug use `TracePoint` feature. 

I guess `TracePoint` hook doesn't work when we load file with `RubyVM::InstructionSequenc.load_from_binary` on Ruby 2.5.
So I posted the issue to Ruby Issue Tracking System.
https://bugs.ruby-lang.org/issues/14702

I think this is why the example on https://github.com/deivid-rodriguez/byebug/issues/452#issuecomment-381358106 work correctly.

**Comment by francoisjacques** [comment]
I have the same issue on an older version of rails where bootsnap was integrated. It uses the same configuration as recommended above and it still breaks in a different spot than where the byebug statement is. If I _strictly_  use `pry` (byebug and pry-byebug are removed from the gemfile) then it breaks at the right place. But I've lost the debugger, which is slightly annoying.

If there's anything I can do to help this issue being fixed (diagnosis, etc), let me know!

**Comment by francoisjacques** [comment]
If I remove `Bootsnap.setup`, to be precise. The gem can be `require`d, as long as `Bootsnap.setup` isn't called.

That's my workaround for now - skip Bootsnap.setup if a environment variable is defined. Not ideal, but it works. I'm sure other folks will hit that shortly.

**Comment by francoisjacques** [comment]
Oh, we're loading an old version of debase as well for interactive debugging from IDEs. I'll see if bumping its version helps.

**Comment by francoisjacques** [comment]
Actually, looking at the change in debase, it's perhaps due to the fact that ruby is used is still at 2.3? In mean, the custom bootsnap configuration might be working for 2.5 and later only?

**Comment by deivid-rodriguez** [comment]
Maybe... The issue @tzmfreedom posted to ruby-core is 2.5 specific, not sure if that could be related.

**Comment by francoisjacques** [comment]
I'll have to put this on the backburner for now, at least I've isolated that removing Bootsnap.setup fixes it, which will do for now. Might get back to this in July. Thanks @deivid-rodriguez !

**Comment by pedrofurtado** [comment]
Shopify/bootsnap#168

**Comment by ndbroadbent** [comment]
byebug was landing me inside a random method (`include?` from `lib/ruby/2.4.0/set.rb`). I'm using Ruby 2.4.3, byebug 10.0.2, bootsnap 1.3.1.

First, I tried deleting the bootsnap cache (`rm -rf tmp/cache/bootsnap-*`) and stopping spring (`./bin/spring stop`), but that didn't fix it. I also tried calling `Bootsnap.setup` with `compile_cache_iseq: false`, but that didn't work. Commenting out all whole `Bootsnap.setup` call fixed byebug. And actually setting all the options `false` also fixed it.  So after some trial-and-error, I figured out that the problem is with the `disable_trace` option. This works for me:

```
  Bootsnap.setup(
    cache_dir:            'tmp/cache',
    development_mode:     true,
    load_path_cache:      true,
    autoload_paths_cache: true,
    disable_trace:        false,
    compile_cache_iseq:   true,
    compile_cache_yaml:   true
  )
```

(And it's fine to keep `compile_cache_iseq: true`.)

**Comment by augustosamame** [comment]
This last Boostnap.setup config fixed it for me in Ruby 2.5.1 / Rails 5.2.1 (previous one did not work).

**Comment by rafaelfranca** [comment]
This is caused by this bug https://bugs.ruby-lang.org/issues/14702. I asked Koichi if this is a bug that can be fixed and the next 2.5 release and he said he'd work on it. I'm also investigating it myself to see if I can help him with a patch.

**Comment by deivid-rodriguez** [comment]
Thanks @rafaelfranca, yeah @tzmfreedom discovered and reported this in https://github.com/deivid-rodriguez/byebug/issues/452#issuecomment-389913382. but there was no movement at all on the ticket. I should've pinged Koichi about it, but I forgot to do it, so thanks so much for helping moving this forward :heart:.

**Comment by deivid-rodriguez** [comment]
Issue has already been [fixed](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/64514/diff) in ruby-core, and it'll be backported to ruby 2.5!

**Comment by tbolt** [comment]
Also experiencing this same issue. Glad to see there is some movement on it.

**Comment by amrendrasingh** [comment]
I am also facing same issue. Really happy to see work around for this.

**Comment by pedrofurtado** [comment]
Guys,

This patch was resolved in Ruby 2.5.3

Also for reference: https://github.com/ruby/ruby/commit/c1034574aa7e6f47843b5533411c75d8196b29d8

**Comment by deivid-rodriguez** [comment]
Thanks for the notice @pedrofurtado!

**Comment by buncismamen** [comment]
I'm using `rails 5.2.2` and `ruby 2.5.3` the problem seems persist

my whole gemfile 

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'
gem 'rails', '~> 5.2.2'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'rack-cors'
gem 'graphql'
gem 'devise'
gem 'jwt'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
```

**Comment by augustosamame** [comment]
I can confirm that installing ruby 2.5.3 or suggested configuration did not solve the problem for me. Only solution was to remove bootsnap

**Comment by andrewjaanuu** [comment]
same with Ruby 2.5.3

**Comment by pouellet** [comment]
I think this is not fixed until 2.5.4 gets released? This seems to be the actual backport that fixed the issue https://bugs.ruby-lang.org/projects/ruby-trunk/repository/ruby_2_5/revisions/66225. Ruby 2.5.3 was released at r65273. Or am I reading this wrong?

**Comment by deivid-rodriguez** [comment]
Yup, it sounds like we have to way until 2.5.4. Just to confirm, ruby 2.6.1 is not affected by this, right?

**Comment by andrewjaanuu** [comment]
tried ruby 2.5.5 and still the same issue

**Comment by Lewiscowles1986** [comment]
Following bootsnap readme and specifying cache folder worked for me. Byebug / Pry like most debuggers will want you to set to single thread

**Comment by FuzzWorley** [comment]
Not trying to point fingers because I know it's not necessarily bootsnap's fault, but this issue has been causing significant confusion and wasted time to our dev team. While the point of the gem is to speed up local dev, it is significantly slowing us down.

After an impact analysis of the effect on production deployments and performance, CCI, and local server boot speed, we found the only benefit of the gem is that it sped up local boot time by almost 10 seconds. However, it's been wasting far more time in loss of debugging tools, causing confusion, and trying to fix the issue ourselves. We are gladly removing the gem from our codebase and will consider adding it back when the issue is truly resolved.
